### ISSUE TITLE
DEB files are corrupted when generated.

### ISSUE THREAD

**Issue by ninoz** [theos/theos#292]
What are the steps to reproduce this issue?
-------------------------------------------
1. … make package to generate the deb file
2. …run dpkg-deb -c generatedfile.deb
3. …observe error due to part of the deb being corrupted

Any logs, error output, etc?
----------------------------

I was trying to compile the following project:
https://github.com/mikaelbo/ProxySwitcher

The project compiles with no errors as follows:
https://ghostbin.com/paste/vrcgy

Testing the resulting deb file shows an error in the archive:
https://ghostbin.com/paste/sfubt

I manually created a deb file using the files in .theos/_/:
```
tar czf ../data.tar.gz [a-z]*
cd DEBIAN
tar czf ../../control.tar.gz *
cd ../..
echo 2.0 > debian-binary
ar r mypackage-42.deb debian-binary control.tar.gz data.tar.gz
```
This parses correctly and installs on the mobile device with no problem.

What versions of software are you using?
----------------------------------------
**Operating System:** … OSX 10.13.2

**Toolchain Version:** … Latest Commit 7a9ec0e  

**SDK Version:** … 9.3

**Comment by uroboro** [comment]
I just downloaded the example project, had to apply a some modifications to have it work with my (patched?) 9.1 sdk. At the top of the main Makefile:

> export TARGET = iphone:clang:9.1:9.1

and renamed

> proxyswitcheruikit/proxyswitcheruikit.plist -> proxyswitcheruikit/ProxySwitcherUIKit.plist

But other than that, `dpkg-deb -c packages/com.mbo42.proxyswitcher_1.0.2-1+debug_iphoneos-arm.deb` shows no error.

The way dm.pl works now is to tar everything in memory and pipe 8KB in and out to a compressor process. This error occurred when I didn't read all the output before closing the pipe, I'm sure I fixed this before having kirb push the changes to Theos.

**Comment by ninoz** [comment]
I just added the change to the plist file and tried to remake the file, i get the same error.

I also tried calling dm.pl directly and again same error.

The version of dpkg-deb i have installed is 1.18.10 _darin-arm64).

**Comment by ninoz** [comment]
I formatted my laptop and reinstalled all the packages and the issue seems to have been resolved.

I'm not sure what could have been causing the issue but Ill close it off.

**Comment by ninoz** [comment]
Sorry false alarm, tar extracts the archive okay but dpkg-deb still fails :(

**Comment by AkdM** [comment]
Hey there, I have the same issue, even if I create a project from scratch.
I also tried to reinstall Theos on macOS, I have the following errors while using `make package install` after exporting `THEOS_DEVICE_IP` and `THEOS_DEVICE_PORT`:

![https://i.imgur.com/i9TsjIP.png](https://i.imgur.com/i9TsjIP.png)

Extracting the `/tmp/_theos_install.deb` generated file on iOS, is resulting the same error.

When I extract the `data.tar.lzma` file on macOS using the `tar tvzf` command, I get the following error:

`tar: Error opening archive: Lzma library error:  No progress is possible`

I then guess that the generated deb is corrupt somehow?

**Comment by DuIslingr** [comment]
@AkdM what macos version? You didn't specify. How did you install perl and stuff?

**Comment by AkdM** [comment]
@DuIslingr that's right. I'm on macOS 10.12.6. I really don't remember how I installed perl (isn't it installed by default on macOS?), but I installed the `IO::Compress::Lzma` with `sudo cpan IO::Compress::Lzma` as on the installation wiki.

Installation of the debs work fine when I build them using the 639c07a commit. The problem appears on 5430240 and newer.
However, when I revert the changes on the `dm.pl` submodule I can't make it work, so I don't really know what is going on.

**Comment by kirb** [comment]
Reverted the change that broke this in a65ff72. The hope was to remove the dependency on `IO::Compress::Lzma` by instead using the `lzma` tool, but the logic used to read the output seems to stop earlier than EOF is sent. Will keep this issue open until @uroboro or myself can look into it.

**Comment by AkdM** [comment]
Thanks @kirb, that indeed works now. Waiting for the upcoming fix too.

**Comment by kirb** [comment]
This was fixed some time ago.
